### ISSUE TITLE
unable to add actor hello in wasmcloud 

### ISSUE THREAD

**Issue by byteshiva** [wasmCloud/examples#127]
Unable to add hello actor in wasmcloud.
wasmcloud.azurecr.io/hello

![image](https://user-images.githubusercontent.com/10637299/148780510-0b286202-4faa-4a90-8f37-e7d51ac2e81c.png)

notes:
ps:
I've plans to build and push actors to local registry

**Comment by byteshiva** [comment]
> You'll need the tag on the image. Just starting `wasmcloud.azurecr.io/hello` isn't enough. For example, the latest version of that is `0.3.2`, so the OCI reference should be `wasmcloud.azurecr.io/hello:0.3.2`

How to get the latest version of an actor,  in this example how can I query the version for `hello`

**Comment by autodidaddict** [comment]
Azure registries don't support queries - what you can do is look at the release list of artifacts in the `examples` repository and it'll give you the version numbers of things.

**Comment by byteshiva** [comment]
> You'll need the tag on the image. Just starting `wasmcloud.azurecr.io/hello` isn't enough. For example, the latest version of that is `0.3.2`, so the OCI reference should be `wasmcloud.azurecr.io/hello:0.3.2`

Still getting the same error!
![image](https://user-images.githubusercontent.com/10637299/148880817-3e365f1c-52c0-4f47-a87b-262d05f9c4b4.png)

**Comment by byteshiva** [comment]
I build a `hello` actor locally and gave absolute path `/home/examples/actor/hello/build/hello_s.wasm` to add Actor to my local hosted wasmcloud.

![image](https://user-images.githubusercontent.com/10637299/148892149-d53ef0d4-1013-4594-89c0-11fdc62ddb77.png)

it worked!

**Comment by byteshiva** [comment]
Had issues in pushing `/home/examples/actor/hello/build/hello_s.wasm` to local registry at port 5000

**Comment by byteshiva** [comment]
> Hey @byteshiva just checking in here, where did we leave off on this? It looks like you're on Linux, but if you're on mac there's a process in the newer OSes that listen on port 5000 and disrupt the local registry

Let me restart the wasm-cloud docker instance with the latest updates and I'll post the errors/updates here.
