### ISSUE TITLE
Content-Type header

### ISSUE THREAD

**Issue by jordan-rash** [wasmCloud/examples#186]
Who's responsibility will it be, actor or provider, to determine the Context-Type of an endpoint?  For example, in the new and improved KV counter, content-type is left blank for the CSS, and the browser is left it infer what it is.  Depending on the browser I am using, I have had the CSS break...I fixed this by adding a header to any endpoint that ended in `.css` inside the provider.

Edit: the default provider behavior does take all headers, that are present from the actor, and append them to the response to the originator.  The issue here is that there is no Content-Type header

https://github.com/wasmCloud/examples/blob/a18e976e0dd1e297ee6c1f55e3066240215cfe91/actor/kvcounter/src/lib.rs#L23

**Comment by brooksmtownsend** [comment]
@jordan-rash I think over time we've gravitated to the actor getting to decide this, like https://github.com/wasmCloud/examples/pull/219. That way you are free to dictate the content type on your own

**Comment by jordan-rash** [comment]
Yea, but the problem was "if the actor doesn't"....I hit that issue with the kvcounter early on.

**Comment by brooksmtownsend** [comment]
Is it just if like, on our side we don't properly handle that in an example?

**Comment by jordan-rash** [comment]
Behavior is different if different browsers.  I handled it in the tailscale httpserver by checking to see if there was a content-type header and if not, I used mime guessing...that fixed the issue for my case (and essentially that is that fixed the issue for me), but that only fixes it in the one httpserver.  None the less, if the answer is "the actors problem", thats enough to close this issue
