### ISSUE TITLE
Use the atomic wasi:keyvalue/atomic interface for WIT-ified kvcounter

### ISSUE THREAD

**Issue by vados-cosmonic** [wasmCloud/examples#229]
Since the rust host has [partial support for the `wasi:keyvalue/atomic` interface](https://github.com/wasmCloud/wasmCloud/pull/555) now, we should update the example `kvcounter-wasmcon2023` actor to use it.

**Comment by vados-cosmonic** [comment]
Hey @rvolosatovs the interface for atomic uses a `u64` which should actually be signed ([at least for Redis](https://redis.io/commands/incr/)). It looks like the contract might have to change here

**Comment by vados-cosmonic** [comment]
Hmnn it looks like this has to be passed up to `wasi-keyvalue` then -- being able to decrement via negative increment feels like a pretty reasonable ask, especially if people are expecting the Redis API... The `kvcounter` example (in the past at least) definitely expected a signed number...

@ricochet are we OK modifying the expectations on the `kvcounter` example  a little to only count up? `wasi-keyvalue` may not change (and probably wouldn't change as fast as we needed it even if they did)...

**Comment by ricochet** [comment]
Yep, our example UI doesn't afford - passing in the delta.
