### ISSUE TITLE
Move examples code into wasmcloud/wasmcloud

### ISSUE THREAD

**Issue by thomastaylor312** [wasmCloud/examples#238]
Multiple community members have expressed confusion akin to "where code?" when they go to our top level repo. Based on community calls, examples made sense as the first thing to see. As part of this, we should be preserving git history when we merge and then it should be presented to the community. 

As part of this, we need to make sure the org maintainers sign off on the repo merge before the work is done

**Comment by vados-cosmonic** [comment]
It seems like it might be reasonable to move only *some* examples into the `wasmcloud/wasmcloud` repo -- maybe some of the more recent components-related work that's been done?

My current idea is to move folders with the newer code from https://github.com/wasmCloud/examples/ to https://github.com/wasmCloud/wasmcloud and go from there?

**Comment by thomastaylor312** [comment]
I feel like that is probably a smart idea

**Comment by connorsmith256** [comment]
Closing since we decided to leave stable ABI examples here
