### ISSUE TITLE
SPIKE/Example: wasmCloud Runtime in/for nomad(?)

### ISSUE THREAD

**Issue by autodidaddict** [wasmCloud/examples#46]

**Comment by brooksmtownsend** [comment]
https://www.nomadproject.io/docs/drivers

**Comment by brooksmtownsend** [comment]
This is an interesting concept, but it would be dramatically changed between running a Rust executable and running the erlang VM. Closing this for now, we should revisit this in the future as we look to support more methods of running wasmcloud (note: we are looking to include a container version in the short term, which would be fully compatible with nomad)
