### ISSUE TITLE
Upgrade all examples to 0.15.0 compliance

### ISSUE THREAD

**Issue by autodidaddict** [wasmCloud/examples#5]
* Remove all dependencies on `wascc-actor`
* Instead add smaller dependencies on the generated crate wrappers in `actor-interfaces`
* Add Go versions for each of the existing Rust examples

**Comment by brooksmtownsend** [comment]
This can be closed once #18 and #19 are closed.

**Comment by brooksmtownsend** [comment]
Done 🎉
