### ISSUE TITLE
Fix failing example releases

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/examples#79]
I recently tagged all actors, interfaces, and providers for release, and some of them failed to release. These should be remediated so we can publish our resources.

Failed at the Rust build step (mostly due to path dependencies in `Cargo.toml`)
- [x] `hello` https://github.com/wasmCloud/examples/actions/runs/1234943831 (Fixed by #85)
- [x] `xkcd` https://github.com/wasmCloud/examples/actions/runs/1234945136
- [x] `factorial` https://github.com/wasmCloud/examples/actions/runs/1234952468 (Fixed by #85)

Failed at the AzureCR release step (mostly due to an unexpected artifact name)
- [x] `echo-messaging` https://github.com/wasmCloud/examples/actions/runs/1234943667
- [x] `example-logging` https://github.com/wasmCloud/examples/actions/runs/1234944395
- [x] `random` https://github.com/wasmCloud/examples/actions/runs/1234945298

**Comment by stevelr** [comment]
hello and factorial should be fixed by https://github.com/wasmCloud/examples/pull/85
